# Auto-built knowledge banks: (stem, correct, explain) lists for domains 3–8.
# Correct strings must be unique within each domain for finalize() distractors.

def z(q: str, c: str, e: str) -> tuple[str, str, str]:
    return (q, c, e)


D3: list[tuple[str, str, str]] = [
    z("Which statement about AES is most accurate?", "AES is a symmetric block cipher standardized by NIST; use authenticated modes like GCM for confidentiality and integrity.", "AES replaced DES; avoid weak modes like ECB for most cases."),
    z("RSA is best described as:", "An asymmetric algorithm for encryption and digital signatures when implemented with proper padding (e.g., OAEP/PSS).", "Key size and padding matter; RSA is not a hash algorithm."),
    z("ECC compared to RSA often provides:", "Comparable security strength with smaller keys and efficient operations on constrained devices.", "Common in modern TLS and mobile platforms."),
    z("Diffie–Hellman key exchange enables:", "Two parties to agree on a shared secret over an insecure channel (authenticate separately to prevent MITM).", "Combine with authenticated channels or signatures."),
    z("A digital signature primarily provides:", "Integrity and non-repudiation for a message when verified with the signer’s public key.", "Different goal than symmetric encryption alone."),
    z("HMAC provides:", "Message authentication using a shared secret and a cryptographic hash.", "Not the same as asymmetric digital signatures."),
    z("SHA-256 is:", "A cryptographic hash producing a fixed-size digest used for integrity verification.", "Hashes are not encryption; passwords should use slow KDFs."),
    z("A PKI provides:", "A framework to issue, distribute, and revoke certificates binding identities to public keys.", "Trust anchors and revocation (CRL/OCSP) are essential."),
    z("OCSP is used to:", "Check near-real-time certificate validity status during TLS verification.", "Stapling can improve performance and privacy."),
    z("Perfect forward secrecy in TLS commonly relies on:", "Ephemeral Diffie–Hellman key exchanges so past sessions resist long-term key compromise.", "Does not mean “perfect” security in all aspects."),
    z("AEAD modes like AES-GCM provide:", "Confidentiality and integrity in one cryptographic construction.", "Prefer over ad hoc MAC-then-encrypt patterns."),
    z("ECB mode is generally a poor choice because:", "Identical plaintext blocks yield identical ciphertext, leaking patterns.", "Use modes with IVs/nonces and authentication."),
    z("Salting password hashes:", "Uses per-user random data so identical passwords yield different hashes, defeating rainbow tables.", "Pair with adaptive KDFs like Argon2/bcrypt."),
    z("Argon2/bcrypt are examples of:", "Adaptive password hashing algorithms designed to resist offline guessing.", "Plain SHA-256 alone is inappropriate for password storage."),
    z("An HSM is used to:", "Generate, protect, and use cryptographic keys in tamper-resistant hardware.", "Common for PKI and payment environments."),
    z("A TPM supports:", "Hardware-rooted key storage, measured boot, and attestation scenarios.", "BitLocker and device identity patterns use TPMs."),
    z("Common Criteria evaluations produce:", "An assurance package with an EAL rating describing evaluated security claims.", "Helps compare products; doesn’t guarantee “unhackable.”"),
    z("The Bell–LaPadula model focuses on:", "Confidentiality in mandatory access control (simple star properties like no read up).", "Biba addresses integrity, not Bell–LaPadula."),
    z("The Biba integrity model emphasizes:", "Rules such as no read down and no write up to protect integrity.", "Contrasts with Bell–LaPadula’s confidentiality focus."),
    z("Clark–Wilson emphasizes:", "Well-formed transactions and separation of duties for commercial integrity.", "CDIs and TPs are core concepts."),
    z("The Brewer–Nash (Chinese Wall) model reduces:", "Conflicts of interest by dynamically constraining access across competitor datasets.", "Common in consulting/finance scenarios."),
    z("A reference monitor enforces:", "Access decisions with complete mediation on every access attempt.", "Should be tamperproof and small enough to analyze."),
    z("The Trusted Computing Base (TCB) is:", "All hardware, firmware, and software critical to enforcing the security policy.", "Minimize TCB size to reduce attack surface."),
    z("Defense in depth means:", "Layering multiple independent controls so one failure does not defeat security.", "Combine administrative, technical, and physical controls."),
    z("Fail secure / fail closed usually means:", "Deny access when a fault or error occurs in a security decision.", "Contrast with fail open, which is rarely acceptable for authorization."),
    z("Economy of mechanism suggests:", "Keep security designs as simple and small as practical.", "Complexity increases bugs and misconfiguration."),
    z("Open design (Kerckhoffs’ principle) states:", "Security should rely on secrecy of keys, not secrecy of the algorithm.", "Algorithms can be public; keys must stay secret."),
    z("Complete mediation requires:", "Every access attempt is checked against policy (including cached decisions when policy changes).", "Missed mediation leads to bypass."),
    z("Least privilege for processes means:", "Grant only the minimum permissions needed for the function.", "Reduces blast radius of compromise."),
    z("Separation of privilege requires:", "Multiple independent conditions to authorize a sensitive action.", "Related to, but not identical to, separation of duties."),
    z("Psychological acceptability means:", "Security controls should be usable enough that people follow them correctly.", "Otherwise users create unsafe workarounds."),
    z("A mantrap / portal helps:", "Prevent tailgating by controlling two interlocking doors.", "Physical layer control."),
    z("A Faraday cage can mitigate:", "Certain electromagnetic emanation/eavesdropping risks for sensitive equipment.", "TEMPEST-style considerations."),
    z("CPTED (environmental design) uses:", "Lighting, visibility, and layout to reduce crime opportunity.", "Complements guards and cameras."),
    z("UPS and generators primarily support:", "Availability during power disruptions for critical systems.", "Align with BCP/DR objectives."),
    z("Fire suppression trade-offs include:", "Balancing personnel safety, equipment damage, and environmental impact.", "Design must match facility risk."),
    z("HVAC controls in data centers protect:", "Equipment from overheating and some environmental failures.", "Humidity and temperature matter."),
    z("Site selection may evaluate:", "Flood, seismic, and other hazards relevant to continuity.", "Geographic risk is part of resilience."),
    z("Tamper-evident seals help:", "Detect unauthorized physical access to devices or enclosures.", "Complements locks and monitoring."),
    z("Air gapping a system:", "Removes network connectivity to reduce remote attack paths.", "Does not eliminate insider or supply-chain risk."),
    z("Stream vs block ciphers contrast as:", "Stream ciphers encrypt units of a stream; block ciphers encrypt fixed-size blocks with modes.", "Examples: AES is block; ChaCha20 is stream."),
    z("Non-repudiation is strongest when:", "Strong digital signatures and reliable identity binding exist.", "Logs alone may be insufficient without crypto proof."),
    z("Downgrade attacks target:", "Protocol/cipher negotiation to force weaker options.", "Remove weak protocols and use strict TLS configuration."),
    z("Certificate pinning can reduce:", "Risk of mis-issued certificates for an application’s expected keys.", "Rotation must be planned to avoid outages."),
    z("OCSP stapling improves:", "TLS performance and privacy by having the server provide a signed OCSP response.", "Reduces client-side OCSP lookups."),
    z("Quantum risk planning includes:", "Considering migration to post-quantum algorithms for long-lived confidentiality.", "Harvest-now/decrypt-later affects data with long secrecy needs."),
    z("Key rotation reduces:", "The window of exposure if a key is compromised.", "Balance operational overhead with risk."),
    z("Crypto agility means:", "Ability to replace algorithms/keys without a full architectural redesign.", "Important as standards evolve."),
    z("Entropy for keys must come from:", "Cryptographically secure random sources, not predictable inputs.", "Weak RNG breaks all downstream crypto."),
    z("Side-channel attacks exploit:", "Timing, power, or electromagnetic leakage from implementations.", "Constant-time crypto implementations mitigate some issues."),
    z("Covert channels transmit:", "Information via unintended paths (storage or timing).", "Hard to eliminate completely in complex systems."),
    z("Homomorphic encryption (conceptually):", "Allows limited computation on ciphertexts under specific schemes with performance trade-offs.", "Not a drop-in replacement for all workloads."),
    z("Format-preserving encryption helps:", "Encrypt data while preserving length/format constraints in legacy systems.", "Still requires proper key management."),
    z("Secure boot helps ensure:", "Only trusted firmware/OS components load at startup.", "Root of trust begins in hardware."),
    z("Remote attestation can:", "Prove a platform’s measured state to a remote verifier (often via TPM).", "Supports zero-trust device posture."),
    z("Memory-safe languages reduce:", "Many memory corruption vulnerability classes compared to unsafe C/C++ patterns.", "Does not remove logic flaws or auth bugs."),
    z("ASLR mitigates:", "Memory exploitation reliability by randomizing address space layout.", "One layer among many exploit mitigations."),
    z("Control-flow integrity aims to:", "Prevent attackers from diverting execution to unintended code.", "Modern compilers and OS features may assist."),
    z("Lattice-based access control uses:", "A partial order of labels/clearances to enforce policy.", "Basis for MLS-style designs."),
    z("Information flow control restricts:", "Where labeled data may move to prevent illicit flows.", "Relevant in high-assurance systems."),
    z("Polyinstantiation can address:", "Conflicts between MLS policy and database rows at different classification levels.", "Multiple versions may exist."),
    z("Take–Grant models analyze:", "How rights propagate through take/grant operations on a protection graph.", "Useful for reasoning about rights expansion."),
    z("The Orange Book (TCSEC) historically:", "Classified systems using trusted computing base concepts (legacy reference).", "Common Criteria largely supersedes in procurement practice."),
    z("EAL (Evaluation Assurance Level) in Common Criteria reflects:", "Increasing rigor of evaluation activities and evidence.", "Higher EAL is not automatically “better product” for all cases."),
    z("Assurance evidence includes:", "Design documentation, tests, and independent evaluation artifacts.", "Supports defensible security claims."),
    z("Secure defaults mean:", "Systems are safe out of the box; risky features require explicit enablement.", "Reduces initial attack surface."),
    z("Fail-safe defaults align with:", "Denying access unless explicitly allowed (default deny).", "Common in firewall and authorization policy."),
    z("Least common mechanism principle:", "Avoids shared mechanisms that could become a single point of compromise across users.", "Isolation reduces coupling."),
    z("Open systems security design prefers:", "Interoperable standards and reviewed algorithms over proprietary obscurity.", "Still must configure correctly."),
    z("A security perimeter mindset alone is insufficient because:", "Insiders and lateral movement exist; zero trust assumes breach.", "Combine network controls with identity and data protections."),
    z("Environmental controls include:", "Temperature, humidity, and water detection for equipment rooms.", "Supports availability and hardware longevity."),
    z("Media transport controls should include:", "Tracking, sealed packaging, and authorized couriers for sensitive media.", "Chain of custody concepts apply."),
    z("Secure firmware updates require:", "Integrity checks and trusted distribution to prevent malicious flashes.", "Supply chain risk includes firmware implants."),
    z("Side-channel countermeasures in crypto implementations include:", "Constant-time algorithms and avoiding secret-dependent branches.", "Library choice matters."),
    z("Key escrow controversies relate to:", "Third-party access to keys for law enforcement vs. broader abuse risk.", "Policy and technical design trade-offs."),
    z("Split knowledge / dual control for master keys means:", "No single person knows or can use the entire key unilaterally.", "Common in ceremonies with HSMs."),
    z("M-of-N threshold schemes enable:", "Reconstructing or using a secret only when enough participants cooperate.", "Useful for recovery without a single custodian."),
    z("Secure engineering reviews should include:", "Threat modeling, crypto misuse checks, and key-management planning.", "Late security is expensive."),
    z("A secure development lifecycle integrates:", "Security activities throughout requirements, design, implementation, and test.", "Shift-left reduces defect cost."),
    z("Physical zoning uses:", "Progressive controls from public to highly sensitive areas.", "Defense in depth physically."),
    z("Mantraps differ from turnstiles in that:", "Mantraps typically interlock two doors to prevent tailgating between spaces.", "Turnstiles control throughput differently."),
    z("Water detection in facilities:", "Helps trigger alarms and shutdowns to protect equipment.", "Part of environmental monitoring."),
    z("Shielding for cabling can reduce:", "EMI/RFI issues and some eavesdropping risks in sensitive environments.", "Design with classified/high-security needs in mind."),
    z("Secure disposal of specialized crypto hardware may require:", "Vendor-specific procedures or destruction when key material cannot be reliably erased.", "Follow policy proportional to sensitivity."),
    z("Design reviews for cryptographic integrations should verify:", "Algorithm/mode suitability, IV/nonce handling, and key lifetimes.", "Misuse is a leading cause of failures."),
]

D4: list[tuple[str, str, str]] = [
    z("TCP is best described as:", "Connection-oriented transport that provides reliability, sequencing, and flow control.", "UDP is connectionless; choose per application needs."),
    z("UDP is often appropriate when:", "Low latency matters and the application tolerates or handles packet loss.", "DNS and some real-time streams use UDP."),
    z("The TCP three-way handshake establishes:", "Connection state before application data transfer (SYN, SYN-ACK, ACK).", "SYN floods target this phase."),
    z("NAT commonly:", "Maps many private addresses to public addresses using connection state.", "Breaks some protocols; impacts end-to-end security visibility."),
    z("A stateful firewall tracks:", "Sessions so return traffic is allowed consistent with established connections.", "Stronger than simple static packet filters."),
    z("Micro-segmentation primarily aims to:", "Restrict east-west traffic between workloads to least privilege.", "Limits lateral movement after initial compromise."),
    z("A screened subnet (DMZ) typically:", "Hosts public services between external and internal networks with strict rules.", "Reduces direct exposure of internal assets."),
    z("TLS primarily protects:", "Data in transit between clients and servers (confidentiality and integrity).", "Does not replace need for server hardening."),
    z("mTLS adds:", "Mutual authentication using client certificates in addition to server authentication.", "Common in service meshes and APIs."),
    z("IPsec tunnel mode often:", "Encapsulates entire IP packets for gateway-to-gateway VPNs.", "Transport mode protects endpoints differently."),
    z("IKE is used to:", "Negotiate IPsec security associations and keys.", "Phase 1/2 parameters must be configured securely."),
    z("GRE tunnels:", "Encapsulate traffic and are often combined with encryption (e.g., IPsec) for confidentiality.", "GRE alone is not inherently encrypted."),
    z("BGP is:", "The inter-domain routing protocol used across the Internet.", "Misconfigurations and hijacks are major risks."),
    z("SD-WAN commonly:", "Uses multiple uplinks with centralized policy and often encrypted overlays.", "Improves performance and resilience."),
    z("DNSSEC provides:", "Integrity and authenticity of DNS records via signatures.", "It does not encrypt queries by itself; consider DoH/DoT for privacy."),
    z("DNS cache poisoning targets:", "Resolver trust by injecting false answers.", "DNSSEC mitigates tampering of signed zones."),
    z("ARP spoofing on a LAN can:", "Associate an attacker’s MAC with another host’s IP address.", "Mitigate with DAI/port security on switches."),
    z("802.1X provides:", "Port-based network access control before granting VLAN access.", "Typically uses EAP and RADIUS."),
    z("RADIUS is frequently used for:", "Centralized authentication for network access and device administration.", "Protect shared secrets; prefer modern transports where possible."),
    z("A reverse proxy often:", "Terminates TLS, filters, and caches requests in front of origin servers.", "Hides internal topology."),
    z("A forward proxy:", "Represents internal users for outbound web access and policy enforcement.", "TLS inspection has privacy and legal implications."),
    z("Email authentication (SPF/DKIM/DMARC) reduces:", "Domain spoofing and improves deliverability trust.", "Not a complete anti-phishing solution."),
    z("S/MIME secures email at:", "The message layer using certificates.", "TLS secures transport between hops; both may be needed."),
    z("VoIP threats include:", "Eavesdropping, toll fraud, and SIP-specific attacks.", "Segment voice traffic and monitor."),
    z("SNMPv3 should be preferred because:", "It supports authentication and encryption.", "v1/v2 community strings are weak."),
    z("SYN flood attacks target:", "TCP connection setup by exhausting half-open connection state.", "Mitigations include SYN cookies and tuning backlog limits."),
    z("DDoS volumetric attacks attempt to:", "Consume bandwidth or session capacity to deny service.", "Mitigate with upstream scrubbing and rate limiting."),
    z("BGP Flowspec can help:", "Drop attack traffic closer to sources with provider cooperation.", "Requires careful policy to avoid collateral damage."),
    z("Network taps vs SPAN:", "Taps are passive and often more reliable under high load than switch mirroring.", "Choose based on fidelity needs."),
    z("NetFlow/IPFIX provides:", "Flow metadata useful for security monitoring and capacity planning.", "Not a replacement for full PCAP everywhere."),
    z("Zero Trust networking emphasizes:", "Explicit verification, least privilege, and assuming breach.", "Identity and device posture are central."),
    z("SASE converges:", "Networking and security services delivered from cloud edges (ZTNA, SWG, CASB concepts).", "Architecture varies by vendor."),
    z("ZTNA differs from classic VPN by:", "Granting per-application access based on identity and context rather than full network trust.", "Reduces implicit lateral access."),
    z("Split tunneling means:", "Only some traffic traverses the VPN tunnel while other traffic goes direct to the internet.", "Impacts security policy enforcement."),
    z("IPv6 neighbor discovery replaces:", "ARP with ICMPv6 mechanisms for address resolution.", "New attack surface to harden."),
    z("Wireless evil twin attacks:", "Impersonate legitimate SSIDs to capture credentials or relay traffic.", "802.1X and careful certificate validation reduce risk."),
    z("WPA3 improves on WPA2 by:", "Stronger handshake protections and better defaults in many cases.", "Migrate when supported by infrastructure."),
    z("Guest Wi‑Fi should be:", "Isolated from internal corporate VLANs.", "Prevents casual lateral movement."),
    z("Bluetooth risks include:", "Weak pairing and proximity attacks.", "Disable unused radios in sensitive areas."),
    z("NFC relay attacks can:", "Extend contactless transactions beyond intended proximity.", "Physical security and issuer controls matter."),
    z("HTTP/3 uses QUIC over UDP, which:", "Changes performance and some security considerations compared to TCP/TLS stacks.", "Firewalls must understand new patterns."),
    z("Certificate Transparency logs help:", "Detect mis-issued certificates by requiring public logging for many CAs.", "Improves accountability."),
    z("HSTS reduces:", "SSL stripping/downgrade risks for sites by enforcing HTTPS for browsers that cached the policy.", "Not a full app security solution."),
    z("OCSP stapling improves:", "TLS handshake efficiency and privacy for revocation status.", "Server provides signed OCSP response."),
    z("DNS over HTTPS (DoH) primarily:", "Encrypts DNS queries to the resolver from local network observers.", "Enterprise visibility trade-offs exist."),
    z("IPv4 private address space (RFC1918):", "Is not routable on the public Internet; NAT maps to public space.", "Still needs internal routing design."),
    z("A bastion/jump host is used to:", "Provide controlled administrative access to sensitive internal systems.", "Often paired with session recording/PAM."),
    z("Network segmentation for PCI often:", "Isolates the cardholder data environment from other networks.", "Reduces scope and blast radius."),
    z("ICS/OT segmentation matters because:", "Legacy protocols and availability requirements differ from IT risks.", "IT/OT convergence increases exposure."),
    z("Lateral movement is limited by:", "Firewall rules, host firewalls, identity controls, and segmentation.", "Assume breach inside the perimeter."),
    z("East-west traffic visibility is important because:", "Attackers move internally after initial compromise.", "NetFlow, EDR, and IDS help."),
    z("TLS inspection (SSL bump) can:", "Decrypt traffic for inspection at enterprise boundaries.", "Legal, privacy, and breakage risks must be managed."),
    z("Weak TLS cipher suites should be:", "Disabled in favor of modern AEAD suites and TLS 1.2+.", "Configuration hygiene matters as much as protocol choice."),
    z("IP fragmentation attacks historically:", "Could confuse IDS/IPS if reassembly differs across devices.", "Normalization and patches reduce risk."),
    z("ICMP should be:", "Filtered thoughtfully—not blindly blocked if needed for operational diagnostics.", "Can be abused for recon and floods."),
    z("Traceroute reveals:", "Hop-by-hop path information.", "Limit exposure where topology is sensitive."),
    z("Port scanning is used to:", "Discover listening services for planning attacks.", "Reduce attack surface and detect scans."),
    z("Banner information can:", "Leak software versions to attackers.", "Minimize verbose banners on internet-facing services."),
    z("DNS rebinding can:", "Trick browsers into accessing internal addresses.", "Browser mitigations and same-site policies help."),
    z("IPv6 extension headers can:", "Complicate inspection and security devices due to chaining and variability.", "Implementations vary; test defenses."),
    z("Wireless IDS/IPS can detect:", "Rogue APs and suspicious 802.11 behavior.", "Sensor placement and tuning matter."),
    z("Captive portals for guest access:", "Authenticate users before granting network access.", "Should not bridge guests to internal resources."),
    z("MACsec (802.1AE) can provide:", "Link-layer encryption on Ethernet where supported.", "Useful in high-sensitivity LANs."),
    z("VPN concentrators should:", "Enforce strong authentication, patch promptly, and log sessions.", "High-value targets."),
    z("Site-to-site VPNs commonly use:", "IPsec policies defining transforms, peers, and interesting traffic.", "Misconfiguration causes outages or leaks."),
    z("Hairpinning in firewall design routes:", "Internal traffic through inspection points when accessing internal resources via external addresses.", "Can affect performance and visibility."),
    z("Reverse DNS and forward DNS consistency:", "Supports mail anti-spam and operational troubleshooting.", "Not a strong security control alone."),
    z("Email gateways should:", "Sandbox attachments, rewrite URLs, and apply anti-spoofing policies.", "Layer with user training."),
    z("Web application firewalls (WAF) help:", "Mitigate common web attacks at the edge.", "Tune rules to reduce bypass and false positives."),
    z("API gateways often provide:", "Authentication, rate limiting, and schema validation for APIs.", "Important for modern application security."),
    z("gRPC/TLS services should:", "Use strong TLS configuration and service identity (mTLS in meshes).", "Protect metadata as well as payloads."),
    z("SSH hardening includes:", "Key-based auth, disabling weak ciphers, and limiting users.", "Jump hosts reduce direct exposure."),
    z("RDP exposure on the internet is risky because:", "It is frequently brute-forced and targeted.", "Prefer VPN/ZTNA and MFA."),
    z("Multicast/broadcast domains should be:", "Right-sized; excessive broadcast domains can harm performance and security visibility.", "VLAN design matters."),
    z("VXLAN overlays:", "Provide L2 segments over L3 networks in data centers.", "Security depends on control plane and segmentation."),
    z("Network access control (NAC) can:", "Quarantine noncompliant endpoints before full access.", "Requires accurate posture assessment."),
    z("Proxy auto-config (PAC) files can be abused if:", "Attackers can tamper with proxy settings or supply chains.", "Protect integrity of endpoint configuration."),
    z("Split DNS (split-horizon) can:", "Serve different answers internally vs externally for the same name.", "Must be managed to avoid leaks."),
    z("DNS ANY queries:", "Are often blocked or rate-limited due to abuse and amplification risks.", "Operational behavior varies."),
    z("SSH tunneling can:", "Bypass network controls if allowed, creating exfiltration paths.", "Restrict egress and monitor."),
    z("Tor and anonymity networks:", "Change threat models for monitoring and attribution.", "Policy and legal considerations apply."),
    z("Satellite links may introduce:", "Latency and jitter affecting security protocols and timeouts.", "Design timeouts accordingly."),
    z("QoS marking can:", "Affect handling during congestion; attackers might abuse markings.", "Validate edge policies."),
    z("IPv6 temporary addresses:", "Improve privacy for clients by rotating interface identifiers.", "Operational impacts on logging/correlation."),
    z("Router/switch management plane must be:", "Protected with strong auth, ACLs, and out-of-band management networks.", "Compromise enables network-wide impact."),
    z("Spanning Tree risks include:", "Topology manipulation if switches are exposed.", "Secure management and BPDU guard features."),
    z("LLMNR/NBT-NS in Windows networks can be abused for:", "Credential relay/interception in some local network attacks.", "Disable where not needed."),
    z("WPAD can:", "Automatically configure proxies; malicious WPAD can intercept traffic.", "Control DHCP/DNS for WPAD carefully."),
]

D5: list[tuple[str, str, str]] = [
    z("Identification is:", "Claiming an identity (e.g., username) before authentication.", "Authentication proves the claim."),
    z("Authentication verifies:", "That a subject is who they claim to be.", "Authorization follows."),
    z("Authorization determines:", "What resources and actions are permitted after authentication.", "Enforced by applications and policy engines."),
    z("Accounting/auditing supports:", "Accountability through logs of actions tied to identities.", "Protect log integrity."),
    z("MFA requires:", "Two or more factors from different categories (know/have/are).", "Two passwords are still one factor."),
    z("Something you have includes:", "A hardware token, smart card, or phone as a possession factor.", "Can be stolen; protect physical devices."),
    z("Something you are refers to:", "Biometric factors like fingerprints or facial recognition.", "Consider privacy and false accept/reject rates."),
    z("Adaptive authentication adjusts:", "Step-up challenges based on risk signals like device or location anomalies.", "Balances security and UX."),
    z("Kerberos uses:", "Tickets from a KDC (TGT and service tickets) for mutual authentication.", "Common in Active Directory environments."),
    z("LDAP directories often:", "Store identities and support bind authentication (prefer LDAPS/TLS).", "Integrate with many apps."),
    z("SAML is commonly used for:", "Browser SSO and exchanging identity assertions between IdP and SP.", "XML-based federation."),
    z("OAuth 2.0 is primarily:", "A framework for delegated authorization.", "Pair with OpenID Connect for authentication semantics."),
    z("OpenID Connect provides:", "Identity layer on OAuth 2.0 using ID Tokens (often JWTs).", "Clarifies authentication vs authorization."),
    z("RBAC assigns permissions through:", "Roles that aggregate privileges aligned to job functions.", "Users receive roles; review periodically."),
    z("ABAC evaluates access using:", "Attributes of subject, object, and environment in policies.", "More flexible than pure RBAC."),
    z("MAC (mandatory access control) uses:", "System-enforced labels users cannot override.", "Common in high-assurance/government systems."),
    z("DAC allows:", "Object owners to grant access at their discretion.", "Weaker than MAC for strict separation."),
    z("Separation of duties requires:", "Different people for conflicting functions (e.g., request vs approve).", "Reduces fraud and insider abuse."),
    z("Least privilege means:", "Grant only the minimum access needed for a task.", "Continuously right-size permissions."),
    z("Need-to-know narrows access to:", "Only the data required for a specific duty.", "Stronger than broad role access."),
    z("Privileged access management (PAM) provides:", "Vaulting, checkout, and session recording for privileged credentials.", "Reduces standing admin rights."),
    z("Just-in-time access grants:", "Elevation only for a limited time window with approval.", "Reduces persistent privilege."),
    z("Federation trusts:", "An external IdP to authenticate users for your applications.", "Metadata exchange and certificate rotation matter."),
    z("Account lifecycle management should:", "Provision, change, and promptly deprovision accounts on termination.", "Orphan accounts are a major risk."),
    z("SCIM helps:", "Automate provisioning to SaaS apps with standardized APIs.", "Reduces manual drift."),
    z("IGA integrates:", "Access reviews, provisioning workflows, and SoD analytics.", "Central governance for identities."),
    z("Access certification campaigns:", "Have managers attest that access remains appropriate.", "Periodic compliance practice."),
    z("SoD rule violations should be:", "Detected and remediated, especially in ERP/finance systems.", "Automation helps at scale."),
    z("OAuth refresh tokens should be:", "Protected, rotated, and bound to clients to reduce leak impact.", "Treat as secrets."),
    z("PKCE mitigates:", "Authorization code interception for public OAuth clients.", "Required for many native/mobile patterns."),
    z("Session fixation is mitigated by:", "Regenerating session IDs after authentication and binding sessions securely.", "Use Secure/HttpOnly/SameSite cookies."),
    z("CSRF protections include:", "Anti-CSRF tokens and SameSite cookies for state-changing requests.", "Validate origin/referrer where appropriate."),
    z("Credential stuffing defenses include:", "MFA, rate limiting, breached-password checks, and CAPTCHA where needed.", "Password reuse is the root issue."),
    z("Passwordless / WebAuthn can provide:", "Phishing-resistant authentication using cryptographic challenges.", "Backup/recovery planning is still required."),
    z("Kerberos delegation risks include:", "Unconstrained delegation allowing excessive impersonation if misconfigured.", "Prefer constrained/resource-based delegation."),
    z("NTLM is considered:", "Legacy and weaker than Kerberos where Kerberos is available.", "Reduce and monitor usage."),
    z("LDAP injection resembles:", "SQL injection but targets directory queries.", "Parameterize and validate inputs."),
    z("SSRF abuses server-side requests to:", "Reach internal services from a vulnerable application.", "Validate URLs, block internal ranges, use egress controls."),
    z("OAuth token audience (aud) must:", "Match the intended resource server to prevent token misuse.", "Validate all JWT claims."),
    z("SAML metadata exchange defines:", "Endpoints, certificates, and entity IDs establishing trust.", "Rotate signing certs with care."),
    z("Step-up MFA may trigger on:", "High-risk actions like wire transfers or new device logins.", "Risk engines drive prompts."),
    z("Identity proofing (IAL) differs from authentication (AAL) because:", "IAL establishes real-world identity strength; AAL establishes authenticator strength.", "NIST 800-63 concepts."),
    z("HRIS-driven provisioning improves:", "Timeliness of joiner/mover/leaver updates.", "Stale HR data causes access errors."),
    z("Service accounts should:", "Use least privilege, avoid interactive login, and rotate secrets.", "Monitor anomalous usage."),
    z("Machine/workload identities use:", "Certificates or cloud workload identities for service-to-service auth.", "SPIFFE/SPIRE patterns help standardize."),
    z("API keys are risky when:", "Embedded in clients or long-lived without rotation.", "Prefer OAuth client credentials with secrets in vaults."),
    z("Cloud IAM policies should:", "Default deny and explicitly allow least privilege.", "Understand evaluation order per cloud."),
    z("Cross-account roles (cloud) require:", "Explicit trust policies defining who can assume roles.", "Least privilege on assume-role."),
    z("Azure AD Conditional Access can enforce:", "MFA, device compliance, and location policies.", "Test to avoid lockouts."),
    z("GCP service account keys are risky because:", "Long-lived JSON keys leak from repos and build artifacts.", "Prefer workload identity federation."),
    z("Privileged cloud roles should use:", "Just-in-time elevation and break-glass procedures.", "Standing global admin is dangerous."),
    z("Directory tiering (AD) separates:", "Tier 0 assets like domain controllers from everyday workstation exposure.", "Protect paths to domain dominance."),
    z("Group Policy can enforce:", "Security baselines, but changes can cause outages if untested.", "Use staging and rollback."),
    z("sudo on Unix improves:", "Auditable privilege elevation versus shared root passwords.", "Centralize logging."),
    z("PAM session recording helps:", "Investigate privileged misuse and meet compliance evidence needs.", "Balance privacy notices."),
    z("Access reviews should include:", "Orphaned accounts, excessive rights, and dormant access.", "Automate data collection."),
    z("Entitlement sprawl in SaaS happens when:", "App owners grant broad access without governance.", "IGA and periodic reviews reduce it."),
    z("OIDC scopes should be:", "Minimal necessary for the client application.", "Avoid over-collecting profile data."),
    z("OAuth consent phishing tricks users into:", "Approving malicious third-party applications.", "Restrict allowed client IDs and educate users."),
    z("Device compliance checks can require:", "Encryption, patch levels, and EDR health before granting access.", "Zero trust device signals."),
    z("Certificate-based authentication needs:", "Protected private keys and lifecycle management.", "Smart cards combine possession + PIN."),
    z("Biometric templates should be:", "Protected and compared with liveness controls where required.", "Templates are sensitive data."),
    z("False accept vs false reject:", "Are tuned based on security vs usability trade-offs for biometrics.", "High-security sites may tune stricter."),
    z("Kerberos golden ticket attacks relate to:", "Compromise of KRBTGT keys leading to forged TGTs in AD environments.", "Defend Tier 0 and monitor anomalies."),
    z("Silver ticket attacks use:", "Forged service tickets when service account keys are stolen.", "Protect service accounts and enable monitoring."),
    z("Pass-the-hash attacks reuse:", "NTLM hashes to authenticate without plaintext passwords.", "Credential hygiene and EDR help."),
    z("Pass-the-ticket attacks reuse:", "Kerberos tickets for lateral movement.", "Shorten ticket lifetimes and monitor unusual usage."),
    z("Shadow credentials in AD can:", "Allow persistence if attackers control attribute-based key material.", "Harden AD and monitor changes."),
    z("OIDC logout complexities arise because:", "Multiple relying parties may have independent sessions.", "Design centralized logout carefully."),
    z("SAML single logout:", "Attempts coordinated logout but can be inconsistent across SPs.", "Test vendor behavior."),
    z("Federation hub simplifies:", "Many-to-one trust versus many pairwise federations.", "Becomes a critical dependency."),
    z("Break-glass accounts should:", "Be monitored, rarely used, and protected with extra controls.", "Alert on any usage."),
    z("Emergency access to IdP outages needs:", "Documented offline/break-glass paths without weakening security permanently.", "Practice recovery."),
    z("Privileged roles in databases should:", "Be limited and monitored; avoid shared DBA passwords.", "Use individual accounts."),
    z("Application roles vs groups:", "Map enterprise groups to app roles with least privilege.", "Avoid local-only role sprawl."),
    z("Dynamic groups (cloud directories):", "Automate membership based on attributes.", "Validate attribute accuracy."),
    z("Access tokens vs ID tokens (OIDC/OAuth):", "Access tokens authorize resource access; ID tokens authenticate identity to the client.", "Don’t send access tokens to browsers casually."),
    z("JWT validation must include:", "Signature, issuer, audience, and expiration checks.", "Algorithm confusion attacks are real."),
    z("Replay protection for auth protocols uses:", "Nonces, timestamps, and short-lived tokens.", "Prevent token reuse."),
    z("Risk-based authentication signals include:", "Impossible travel, new device, and unusual time-of-day patterns.", "Tune false positives."),
    z("Password policies should align with:", "Modern guidance emphasizing length and breach checks over forced excessive rotation.", "NIST SP 800-63B evolves practices."),
    z("Hardware security keys (FIDO2) can provide:", "Strong phishing-resistant authentication.", "Plan backup factors."),
    z("Account lockout policies should balance:", "Brute-force defense vs denial-of-service against accounts.", "Use risk-based throttling where possible."),
    z("Directory hardening includes:", "Protecting DCs, restricting LDAP binds, and monitoring replication.", "AD is a crown jewel."),
    z("Cloud identity federation to on-prem apps uses:", "Protocols like SAML/OIDC via identity bridges.", "Watch token mapping and claims."),
    z("Just-in-time VM access in clouds can:", "Reduce standing network permissions to sensitive resources.", "Combine with approvals and logging."),
]

D6: list[tuple[str, str, str]] = [
    z("Vulnerability scanning primarily:", "Identifies known issues and misconfigurations at scale.", "Validate and prioritize—not every finding is exploitable."),
    z("Penetration testing:", "Simulates attacker techniques within agreed rules to assess exploitability and impact.", "Differs from a full red team campaign in scope and stealth."),
    z("Red team engagements typically:", "Emulate adversaries over longer periods with broader objectives than a point-in-time pentest.", "Measure detection and response, not only vulnerabilities."),
    z("Purple team exercises:", "Align offensive tests with defensive improvements and detection engineering.", "Closes gaps faster than siloed testing."),
    z("Black box testing assumes:", "No internal implementation knowledge (external attacker view).", "May miss deeper issues quickly."),
    z("White box testing provides:", "Full knowledge including source and architecture.", "Often finds issues faster with deeper review."),
    z("SAST analyzes:", "Source or bytecode without executing the program.", "Early feedback; can have false positives."),
    z("DAST tests:", "Running applications externally.", "Good for staging; may miss auth-only issues without setup."),
    z("IAST combines:", "Runtime instrumentation with code-aware analysis.", "Can reduce false positives vs SAST/DAST alone."),
    z("SCA identifies:", "Vulnerable third-party components and license risks.", "Critical for supply chain security."),
    z("Fuzzing is effective for:", "Finding crashes and vulnerabilities in parsers and protocol stacks.", "Combine with sanitizers in dev."),
    z("CVSS base scores reflect:", "Technical severity of a vulnerability independent of your environment.", "Combine with threat intel and asset criticality."),
    z("EPSS estimates:", "Probability of exploitation in the wild.", "Helps prioritize patching beyond CVSS alone."),
    z("Patching SLAs should be:", "Risk-based, considering exploitability and compensating controls.", "Emergency processes for active exploitation."),
    z("Authenticated scans improve:", "Visibility into host patch levels when credentials are provided.", "Scope and safety controls required."),
    z("Compliance audits assess:", "Whether controls meet policy/regulatory requirements.", "Compliance does not guarantee security."),
    z("SOC 2 reports provide:", "Third-party attestation on trust services criteria relevant to services.", "Type II covers a period of operating effectiveness."),
    z("ISO 27001 certification audits:", "Evaluate whether an ISMS is implemented and continually improved.", "Statement of Applicability maps controls."),
    z("PCI DSS assessments include:", "Scanning and segmentation testing for in-scope environments.", "Reduce scope where possible."),
    z("Evidence for audits should be:", "Sufficient, reliable, and retained per policy.", "Tamper-evident storage strengthens defensibility."),
    z("Internal audits should be:", "Independent of the audited function to reduce bias.", "May still be internal staff."),
    z("Sampling in audits:", "Selects a subset of controls/transactions when full review is impractical.", "Risk determines sample size."),
    z("Remediation validation confirms:", "Fixes work and don’t introduce regressions.", "Close findings formally."),
    z("False positives require:", "Tuning and triage to keep teams trusting results.", "Otherwise findings are ignored."),
    z("Bug bounties:", "Incentivize coordinated disclosure within defined scope.", "Don’t replace secure development."),
    z("Safe harbor in bug bounties:", "Provides legal clarity for good-faith research within rules.", "Define clearly."),
    z("Phishing simulations:", "Measure user susceptibility and training effectiveness.", "Handle privacy/ethics carefully."),
    z("Social engineering tests require:", "Explicit authorization and narrow scope.", "Can harm trust if mishandled."),
    z("Physical penetration tests evaluate:", "Guards, locks, tailgating, and entry controls.", "Coordinate with legal and safety."),
    z("Wireless assessments include:", "Weak encryption, rogue AP detection, and credential attacks.", "Segment guest and corporate Wi‑Fi."),
    z("Cloud configuration reviews find:", "Public buckets, overly broad IAM, and missing logging.", "CSPM automates checks."),
    z("Container image scanning catches:", "Vulnerable OS packages and malware in layers.", "Run in CI/CD."),
    z("Kubernetes assessments review:", "RBAC, admission controls, network policies, and secrets handling.", "Misconfigurations are common."),
    z("API security testing focuses on:", "Broken object authorization, excessive data exposure, and weak auth.", "OWASP API Top 10 guidance."),
    z("Business logic testing finds:", "Flaws scanners miss because workflows require domain understanding.", "Often manual."),
    z("Regression security tests ensure:", "Fixes don’t reintroduce vulnerabilities.", "Automate in pipelines."),
    z("CI quality gates can fail builds on:", "Critical SAST/SCA findings per policy.", "Tune thresholds to reduce noise."),
    z("Threat modeling improves testing by:", "Prioritizing likely attack paths and abuse cases.", "STRIDE helps categorize threats."),
    z("Attack surface management:", "Continuously discovers internet-facing assets and exposures.", "Shadow IT visibility."),
    z("Penetration test reports should:", "Provide clear impact, likelihood, evidence, and remediation guidance.", "Executive summary plus technical detail."),
    z("Retests after remediation:", "Verify vulnerabilities are resolved.", "Professional testing includes closure evidence."),
    z("Rules of engagement define:", "Allowed targets, techniques, timing, and emergency contacts.", "Legal agreement required."),
    z("Denial-of-service testing must be:", "Performed in isolated environments or with explicit coordination.", "Avoid impacting production."),
    z("Cryptographic assessments verify:", "Algorithm choices, key lengths, and secure randomness.", "Misconfiguration is common."),
    z("TLS scanning checks:", "Protocols, cipher suites, and certificate issues.", "Harden configurations continuously."),
    z("Segmentation tests validate:", "That ACLs actually block assumed paths.", "Assume breach testing."),
    z("Data exfiltration tests (authorized) validate:", "DLP and egress controls.", "Scope and privacy considerations apply."),
    z("Secure SDLC maturity models (e.g., SAMM) help:", "Benchmark and improve security practices across development.", "Continuous improvement."),
    z("Security champions programs:", "Embed security advocates within dev teams.", "Scales governance."),
    z("Developer training improves:", "Secure coding practices and fewer repeat vulnerability classes.", "Measure with metrics."),
    z("Third-party attestations can reduce:", "Direct testing burden if risks are acceptable.", "Still review contracts and scope."),
    z("Continuous compliance monitoring:", "Automates evidence collection for controls.", "Reduces audit scramble."),
    z("Privacy assessments (PIA/DPIA) focus on:", "Personal data processing risks and mitigations.", "Partner with legal/privacy."),
    z("License compliance in SCA avoids:", "Legal issues from copyleft violations.", "Policy enforcement in CI."),
    z("SLSA levels describe:", "Increasing integrity assurances for software supply chains.", "Higher levels are harder to achieve."),
    z("Signed artifacts and attestations help:", "Verify build provenance and integrity.", "Part of supply chain security."),
    z("Firmware testing includes:", "Version verification and integrity checks.", "Supply chain risk."),
    z("Binary analysis can detect:", "Malware implants or suspicious behaviors in acquisitions.", "Due diligence use case."),
    z("Hardware trojans are:", "Difficult to detect without trusted supply chain controls.", "Nation-state concern."),
    z("Performance testing can reveal:", "DoS weaknesses under load.", "Coordinate with security testing."),
    z("Mutation testing measures:", "Test suite effectiveness by mutating code.", "Different from security fuzzing."),
    z("Coverage-guided fuzzing evolves inputs using:", "Feedback like code coverage to find deeper bugs.", "Very effective for parsers."),
    z("Benchmark scanning (CIS/DISA) helps:", "Compare configurations to hardening baselines.", "Tune exceptions carefully."),
    z("SIEM content testing uses:", "Known-bad telemetry or atomic tests to validate detections.", "Purple teaming aligns."),
    z("Tabletop exercises for IR:", "Validate plans and roles without technical exploitation.", "Cheap improvement."),
    z("Incident response tabletop supports audits by:", "Demonstrating preparedness evidence.", "Document outcomes."),
    z("Key VM metrics include:", "Mean time to remediate criticals and aging backlog.", "Leadership reporting."),
    z("Risk acceptance for findings requires:", "Documented owner and rationale.", "Not silent acceptance."),
    z("Chain of custody for test artifacts:", "Supports legal use if testing triggers incidents.", "Document storage and access."),
    z("Peer review of findings reduces:", "False positives and improves remediation advice.", "Senior oversight helps."),
    z("Quality of tickets affects remediation:", "Clear reproduction steps speed fixes.", "Include evidence and impact."),
    z("Secure test data avoids:", "Using production personal data in lower environments.", "Synthetic/masked data preferred."),
    z("Environment parity issues can cause:", "Findings that don’t reproduce in production or vice versa.", "Align configurations."),
    z("Scoped credentials for scanning reduce:", "Blast radius if scan credentials leak.", "Use least privilege scan accounts."),
    z("Authenticated web scanning needs:", "Test accounts and workflows configured safely.", "Avoid destructive tests."),
    z("API fuzzing targets:", "Parameter combinations and schema violations.", "Rate limits may interfere—coordinate."),
    z("Mobile app assessments review:", "Local storage, transport security, and reverse engineering resistance.", "Certificate pinning trade-offs."),
    z("Thick client assessments review:", "Update channels, crypto libraries, and local secrets handling.", "Binary protections vary."),
    z("Mainframe assessments may focus on:", "RACF/ACF2/Top Secret configurations and privileged users.", "Specialized skills."),
    z("Database assessments check:", "Default accounts, excessive privileges, and injection risks.", "Encrypt sensitive columns."),
    z("Logging configuration reviews ensure:", "Security events are captured with adequate detail and integrity.", "Blind spots hide incidents."),
    z("Backup configuration reviews verify:", "Encryption, immutability, and restore testing.", "Ransomware resilience."),
    z("Firewall rule reviews look for:", "Any-any rules, overly broad permits, and unused rules.", "Change management alignment."),
    z("WAF tuning requires:", "Balancing false positives vs effective blocking.", "Iterative improvement."),
    z("DAST authentication scripting:", "Must be maintained as apps change.", "Broken login scripts miss authenticated tests."),
    z("SAST rule customization:", "Reduces noise by aligning to frameworks and libraries used.", "Requires expertise."),
    z("Container escape testing validates:", "That workloads cannot break out to the host.", "CIS benchmarks help."),
    z("Supply chain reviews include:", "Vendor SDLC practices and dependency update policies.", "Contracts and SLAs matter."),
]

D7: list[tuple[str, str, str]] = [
    z("An IR plan should define:", "Roles, severity levels, communications, and escalation paths.", "Prepare before incidents."),
    z("Containment aims to:", "Limit damage while preserving evidence as appropriate.", "Balance with business continuity."),
    z("Eradication removes:", "Malware, persistence, and unauthorized accounts from the environment.", "Follow with verification hunts."),
    z("Recovery restores:", "Services to normal operation with heightened monitoring.", "Validate integrity after rebuild."),
    z("Lessons learned should:", "Update playbooks, controls, and training based on real incidents.", "Blameless postmortems help."),
    z("Chain of custody for evidence:", "Documents handling to support legal and forensic use.", "Breaks weaken admissibility."),
    z("Forensic imaging:", "Copies media with hashes for analysis on duplicates.", "Avoid working directly on originals."),
    z("Volatile data collection prioritizes:", "RAM and live artifacts before powering off.", "Order of volatility matters."),
    z("SIEM correlation:", "Matches log patterns to generate alerts for triage.", "Tune to reduce false positives."),
    z("SOAR orchestration:", "Automates playbook steps for common alert types.", "Requires mature content and safeguards."),
    z("EDR provides:", "Endpoint telemetry and response beyond signature AV.", "Critical for modern threats."),
    z("XDR aims to:", "Correlate signals across endpoints, email, identity, and network (vendor-defined).", "Not a magic replacement for staff."),
    z("SOC tiers commonly:", "Triage (T1), deeper investigation (T2), advanced/hunt (T3).", "Clear escalation paths."),
    z("MTTD measures:", "Mean time to detect an incident.", "Shorter is better with defined scope."),
    z("MTTR definitions vary:", "Clarify whether respond or recover; align metrics across teams.", "Avoid apples-to-oranges reporting."),
    z("Runbooks standardize:", "Operational response steps for repetitive alerts.", "Reduce variance and speed."),
    z("IR playbooks guide:", "Decision-making for incident classes like ransomware or BEC.", "Update after each major case."),
    z("Threat hunting is:", "Proactive hypothesis-driven searching for hidden adversaries.", "Beyond waiting for alerts."),
    z("IOC feeds provide:", "Indicators like IPs, hashes, and domains for detection.", "Expire stale IOCs to reduce noise."),
    z("TTP-based detections align to:", "Behaviors mapped to frameworks like MITRE ATT&CK.", "Harder for attackers to change than IOCs."),
    z("Log retention balances:", "Investigation needs, cost, and privacy/legal constraints.", "Define per log source."),
    z("NTP/time sync matters because:", "Correlating events across systems requires aligned clocks.", "Forensics depends on accurate timestamps."),
    z("Log integrity protections include:", "Immutable storage, signing, and restricted access.", "Attackers target logs."),
    z("On-call rotations ensure:", "Coverage for critical alerts after hours.", "Manage fatigue and handoffs."),
    z("Incident severity levels help:", "Allocate resources and executive engagement appropriately.", "Define criteria up front."),
    z("Crisis communications during incidents:", "Coordinate legal, PR, and regulatory obligations.", "Don’t improvise messaging."),
    z("Breach notifications may be required:", "Within specific timelines depending on jurisdiction and data types.", "Legal counsel guides."),
    z("Ransomware response often begins with:", "Isolation, evidence preservation decisions, and leadership activation.", "Paying ransom is a business/legal decision."),
    z("Backup strategy 3-2-1 means:", "Three copies, two media types, one offsite.", "Test restores, not just backups."),
    z("Immutable backups help against:", "Ransomware that attempts to encrypt or delete backups.", "Object lock/WORM patterns."),
    z("DR testing validates:", "Whether RTO/RPO objectives are achievable.", "Tabletop vs full failover trade-offs."),
    z("Hot/warm/cold sites differ in:", "Readiness versus cost for alternate processing.", "Match to MTD and budget."),
    z("Alternate workforce plans address:", "Pandemics and unavailable critical staff.", "Cross-training and backups."),
    z("Cloud IR requires:", "Understanding logging sources, snapshots, and IAM in the provider.", "Shared responsibility applies."),
    z("Kubernetes IR challenges include:", "Ephemeral pods and image provenance analysis.", "Collect artifacts quickly."),
    z("Memory forensics helps:", "Detect rootkits and in-memory malware.", "Specialized tooling and skills."),
    z("Network forensics uses:", "PCAPs and flow data to trace lateral movement.", "Retention and privacy constraints."),
    z("Email forensics examines:", "Headers, rules, and mailbox changes for BEC.", "Business context matters."),
    z("Insider threat programs:", "Balance monitoring with privacy and labor law requirements.", "Policy transparency."),
    z("UEBA detects anomalies:", "Compared to learned baselines of user and entity behavior.", "Tune for seasonality."),
    z("Honeypots can:", "Divert attackers and collect intelligence.", "Isolate to avoid collateral risk."),
    z("Deception technology expands:", "Decoys and breadcrumbs beyond simple honeypots.", "Operational overhead exists."),
    z("Malware sandboxes:", "Execute suspicious files in isolation to observe behavior.", "Avoid leaking C2 in production networks."),
    z("YARA rules detect:", "Patterns in files and memory for malware families.", "Community rules need tuning."),
    z("Sigma rules help:", "Describe detections portably for translation to SIEM queries.", "Community content varies in quality."),
    z("MITRE ATT&CK mapping:", "Aligns detections and incidents to adversary techniques.", "Improves coverage assessments."),
    z("Purple team outputs:", "Should drive prioritized detection backlog items.", "Measure improvements over time."),
    z("Post-incident reviews should be:", "Blameless and focused on systemic fixes.", "Culture enables learning."),
    z("SOC effectiveness metrics include:", "True positive rate, backlog age, and analyst throughput.", "Avoid vanity metrics."),
    z("Alert fatigue leads to:", "Missed real incidents when analysts ignore noisy alerts.", "Tune, deduplicate, automate safely."),
    z("Automation safeguards:", "Prevent destructive containment without approvals and guardrails.", "Humans remain accountable."),
    z("Patch management balances:", "Security risk vs uptime during changes.", "Emergency patches happen."),
    z("Change management reduces:", "Outages from uncontrolled changes.", "Security depends on stable operations."),
    z("Configuration drift:", "Increases risk when systems deviate from hardened baselines.", "Continuous compliance scanning helps."),
    z("Zero-day response may require:", "Compensating controls until patches exist.", "Threat intel guides prioritization."),
    z("Threat intel must be:", "Actionable and relevant to your environment.", "Feeds alone aren’t strategy."),
    z("Ticket quality improves IR when:", "Analysts capture scope, timeline, and impacted assets clearly.", "Handoffs depend on it."),
    z("Shift handoffs should include:", "Active incidents, anomalies, and ongoing hunts.", "Written passdown reduces lossy memory."),
    z("Security monitoring scope includes:", "Identity, endpoint, network, email, and cloud control planes.", "Gaps hide attacks."),
    z("Cloud audit logs (e.g., CloudTrail) are critical for:", "Investigating API misuse and misconfiguration changes.", "Protect logs from tampering."),
    z("Object storage logging/versioning helps:", "Investigate data exfiltration and accidental overwrites.", "Not always enabled by default."),
    z("Email gateway defenses include:", "Sandboxing attachments and URL rewriting.", "Layer with authentication policies."),
    z("DNS logging helps detect:", "C2 domains and DNS tunneling attempts.", "Privacy and retention policies apply."),
    z("Proxy logs assist investigations of:", "User-driven downloads and web C2.", "TLS inspection trade-offs."),
    z("VPN logs can show:", "Unusual locations, concurrent sessions, and shared accounts.", "Correlate with IdP logs."),
    z("Physical theft incidents may trigger:", "IR for device loss and potential data exposure.", "Full-disk encryption reduces impact."),
    z("BCP activation criteria should be:", "Predefined to avoid hesitation during crises.", "Practice decision-making."),
    z("Incident commander role:", "Coordinates response and communications with a single accountable lead.", "Reduces confusion."),
    z("After-action reports:", "Capture improvements and evidence for future audits.", "Store lessons in a knowledge base."),
    z("Cyber insurance claims:", "Require documentation and may mandate vendor forensics.", "Understand policy exclusions."),
    z("Law enforcement engagement:", "Should be planned with legal counsel and evidence preservation.", "Don’t destroy logs."),
    z("Public statements during breaches:", "Must align facts and legal obligations; avoid speculation.", "Coordinate PR and legal."),
    z("Monitoring privileged users:", "Detects insider misuse and account takeover of powerful accounts.", "PAM session recording helps."),
    z("Service account monitoring:", "Flags unusual auth sources and off-hours usage.", "Often targeted in attacks."),
    z("Windows persistence via scheduled tasks:", "Should be monitored for suspicious creation/modification.", "Sysmon helps."),
    z("WMI abuse can enable:", "Lateral movement and persistence in Windows environments.", "Detection content exists."),
    z("PowerShell logging improves:", "Visibility into scripting abuse when properly configured.", "Constrained language mode trade-offs."),
    z("Linux auditd can record:", "Syscalls and file integrity events with tuned rules.", "Performance impact requires tuning."),
    z("Container runtime monitoring:", "Detects suspicious syscalls and escape attempts.", "eBPF tooling is emerging."),
    z("Network segmentation aids containment:", "By isolating compromised segments quickly.", "Pre-planned isolation VLANs help."),
    z("Evidence preservation in cloud:", "Requires snapshots, memory captures (where possible), and log exports before retention expires.", "Time is critical."),
    z("Ransomware negotiation considerations include:", "Legal counsel, sanctions, and whether payment is lawful/insurable.", "Not purely technical."),
    z("Business continuity during cyber events may use:", "Alternate processing and manual workarounds documented in BCP.", "Test these paths."),
    z("Crisis leadership communications:", "Should be coordinated with facts known at each stage.", "Avoid premature blame."),
    z("Tabletop for supply-chain compromise:", "Tests vendor coordination and forensic data sharing.", "Contracts should anticipate this."),
    z("Monitoring DNS over HTTPS on endpoints:", "May be harder at the network edge; use endpoint visibility.", "Policy and privacy trade-offs."),
    z("SOAR playbooks for phishing:", "Should include triage, containment, and user notification steps.", "Automate safe parts only."),
    z("IR retainer relationships:", "Can accelerate vendor support during major incidents.", "Define SLAs."),
    z("Forensic vendor engagement:", "Should preserve independence and chain of custody.", "Define evidence handling."),
    z("Communications with regulators:", "Often must be timely and factual; legal leads messaging.", "Jurisdiction-specific."),
    z("Customer support during incidents:", "May need scripted responses to reduce inconsistent disclosures.", "Train teams."),
    z("Monitoring cloud IAM changes:", "Detects attacker persistence via new users, roles, or keys.", "Alert on privilege escalations."),
    z("Kubernetes audit logs:", "Record API actions important for investigations.", "Protect audit storage."),
    z("Serverless function monitoring:", "Should include invocation anomalies and IAM misuse.", "Cold start issues complicate baselines."),
    z("Data exfiltration monitoring:", "Combines DLP, NetFlow, and endpoint uploads.", "Tune for business workflows."),
    z("Insider investigations require:", "HR/legal partnership and careful evidence handling.", "Privacy matters."),
    z("Post-incident control improvements:", "Should be tracked to completion with owners.", "Close the loop."),
    z("Metrics for detection coverage:", "May map ATT&CK techniques to logged/alerted status.", "Identify blind spots."),
    z("Hunt hypotheses should be:", "Based on intelligence and environmental knowledge.", "Document outcomes."),
    z("Incident timelines:", "Are built from correlated logs and interviews; accuracy matters for legal cases.", "NTP sync helps."),
    z("Containment verification ensures:", "Attackers no longer have access before declaring recovery.", "Hunt for persistence."),
]

D8: list[tuple[str, str, str]] = [
    z("Shift-left security means:", "Integrating security early in requirements, design, and implementation.", "Cheaper than late fixes."),
    z("Threat modeling helps teams:", "Identify threats and mitigations before coding.", "STRIDE categorizes common threat types."),
    z("Secure requirements should specify:", "Authentication, authorization, data sensitivity, and logging needs.", "Make security testable."),
    z("Abuse cases complement user stories by:", "Describing attacker misuse scenarios.", "Improves test design."),
    z("SAST is most effective when:", "Integrated into developer workflows and CI with tuned rules.", "Reduce false positives."),
    z("DAST requires:", "A running environment and realistic test data/setup.", "Good for pre-release testing."),
    z("SCA should run:", "On every build to catch newly introduced vulnerable dependencies.", "Fail builds on criticals per policy."),
    z("Secrets scanning prevents:", "Committing API keys and passwords to repositories.", "Rotate secrets if leaked."),
    z("IaC scanning checks:", "Terraform/CloudFormation for risky misconfigurations.", "Policy as code gates."),
    z("SBOMs improve:", "Transparency for vulnerability response across components.", "Increasingly expected by customers/regulators."),
    z("Secure SDLC includes:", "Training, design review, testing, and release gates.", "Maturity models like SAMM help."),
    z("OWASP ASVS provides:", "Verifiable security requirement levels for applications.", "Use as a checklist by level."),
    z("Injection defenses rely on:", "Parameterized queries and strong input validation.", "Never concatenate SQL with user input."),
    z("XSS defenses include:", "Contextual output encoding and Content Security Policy.", "HttpOnly cookies protect session tokens from JS."),
    z("CSRF defenses include:", "Anti-CSRF tokens and SameSite cookies.", "Protect state-changing requests."),
    z("Insecure deserialization can cause:", "Remote code execution via crafted objects.", "Avoid unsafe native deserialization."),
    z("SSRF defenses validate:", "Outbound URLs/hosts and block access to internal ranges as needed.", "DNS rebinding protections."),
    z("Broken access control means:", "Users can access objects or actions outside their authorization.", "Test every endpoint and object ID."),
    z("Security misconfiguration includes:", "Default accounts, open directories, and verbose errors.", "Harden baselines continuously."),
    z("Vulnerable components arise from:", "Outdated libraries with known CVEs.", "Automate updates with testing."),
    z("Security logging failures:", "Prevent detection and investigation.", "Protect logs from tampering and redact secrets."),
    z("Cryptographic failures include:", "Weak algorithms, hard-coded keys, and poor randomness.", "Use vetted libraries."),
    z("Rate limiting helps mitigate:", "Brute force and some denial-of-service abuse.", "Per-IP and per-account limits."),
    z("Input validation should prefer:", "Allowlists over denylists where possible.", "Reject unexpected types and lengths."),
    z("Output encoding depends on:", "HTML, JS, URL, and CSS contexts.", "One encoding does not fit all."),
    z("CSP reduces:", "XSS impact by restricting script sources.", "Start with report-only mode."),
    z("Subresource Integrity (SRI) helps:", "Verify third-party script integrity.", "Use with CDNs."),
    z("Secure cookie flags include:", "HttpOnly, Secure, and appropriate SameSite settings.", "Not a substitute for solid session design."),
    z("Session fixation mitigation:", "Regenerate session IDs after authentication.", "Bind sessions carefully to avoid breaking UX."),
    z("Password storage must use:", "Adaptive hashing with per-user salts for verifier storage.", "Never MD5/SHA1 for passwords."),
    z("OAuth implementations must validate:", "state, redirect URI, and token audiences.", "Prevent token theft and mix-up attacks."),
    z("JWT pitfalls include:", "Algorithm confusion, weak secrets, and missing claim validation.", "Use mature libraries only."),
    z("CORS misconfiguration can:", "Allow untrusted sites to access APIs with user credentials.", "Restrict allowed origins."),
    z("File upload risks include:", "Malware uploads and path traversal.", "Validate type, size, and store outside web root."),
    z("Path traversal defenses:", "Canonicalize paths and restrict to intended directories.", "Avoid passing user paths to FS APIs raw."),
    z("Command injection arises when:", "User input reaches OS shells.", "Use APIs instead of shelling out."),
    z("LDAP injection occurs when:", "User input is concatenated into directory queries.", "Parameterize queries."),
    z("XML bombs target:", "Parser resource exhaustion via entity expansion.", "Disable risky XML features."),
    z("ReDoS issues come from:", "Catastrophic backtracking in regex engines.", "Review regexes used on untrusted input."),
    z("Prototype pollution (JS) happens when:", "Unsafe deep merges let attackers modify prototypes.", "Sanitize merge inputs."),
    z("Race conditions/TOCTOU can affect:", "Security checks and file operations in concurrent workflows.", "Use transactions/locks."),
    z("Memory-safe languages reduce:", "Many memory corruption classes.", "Logic flaws remain."),
    z("Mobile apps must not ship:", "Long-lived secrets in binaries.", "Server-side controls hold secrets."),
    z("Certificate pinning trade-offs:", "Stronger MITM resistance but harder rotation.", "Plan update channels."),
    z("WebView bridges can be risky when:", "JavaScript can call native code without strict validation.", "Validate messages."),
    z("GraphQL risks include:", "Over-fetching, batching abuse, and authZ gaps.", "Use complexity limits and authZ per object."),
    z("REST IDOR is:", "Insecure direct object reference allowing unauthorized object access.", "Authorize per resource instance."),
    z("Mass assignment allows:", "Clients to set sensitive fields like admin flags.", "Allowlist updatable fields."),
    z("Insecure CI/CD can leak:", "Secrets via logs, artifacts, and caches.", "Mask secrets; scan pipelines."),
    z("Dependency confusion attacks:", "Trick package managers into installing malicious packages.", "Use private registries and scoped names."),
    z("Typosquatting packages:", "Mimic popular libraries.", "Verify publisher and integrity hashes."),
    z("Branch protection should:", "Require reviews and block force pushes.", "Protect main/release branches."),
    z("Code review catches:", "Business logic flaws and dangerous patterns.", "Security champions improve quality."),
    z("Secure defaults in frameworks:", "Reduce insecure starter apps.", "Still configure for production."),
    z("Environment separation prevents:", "Production data leaking into dev/test.", "Use synthetic data."),
    z("Logging must avoid:", "Writing secrets and excessive PII to logs.", "Redact and classify logs."),
    z("Error messages to users should avoid:", "Stack traces and internal details.", "Log details server-side only."),
    z("Security headers (HSTS, X-Frame-Options) reduce:", "Downgrade and clickjacking risks.", "Tune for your application."),
    z("Clickjacking is mitigated by:", "CSP frame-ancestors and legacy frame-busting patterns.", "UI redress attacks."),
    z("DOM XSS occurs when:", "Client-side code writes untrusted data into the DOM unsafely.", "Prefer safe APIs and sanitization."),
    z("Stored XSS persists:", "Malicious scripts in stored content viewed by other users.", "Encode on output consistently."),
    z("Reflected XSS reflects:", "Input in responses without encoding.", "Mostly input handling and context encoding."),
    z("SQLi blind techniques infer data via:", "Boolean or timing channels.", "Parameterized queries fix the class."),
    z("NoSQL injection manipulates:", "Operators and types in document queries.", "Validate inputs strictly."),
    z("SSTI occurs when:", "User input is evaluated as template code.", "Never evaluate untrusted templates."),
    z("Rolling your own crypto is:", "Strongly discouraged; use vetted libraries and patterns.", "Subtle mistakes are common."),
    z("Constant-time comparisons help with:", "Reducing timing attacks on secrets like tokens.", "Use library helpers."),
    z("Secure random tokens require:", "CSPRNG APIs, not predictable PRNGs.", "Predictable tokens break auth."),
    z("Thread safety issues can create:", "TOCTOU problems in security checks.", "Synchronize correctly."),
    z("Kubernetes secrets at rest:", "May be only base64 unless encryption at rest is enabled.", "Restrict RBAC to Secret objects."),
    z("Helm charts should be reviewed for:", "Overly broad RBAC and unpinned images.", "Supply chain hygiene."),
    z("Serverless IAM roles should be:", "Least privilege per function.", "Overly broad roles are common."),
    z("Webhooks must verify:", "Signatures and timestamps to prevent spoofing and replay.", "Rotate signing secrets."),
    z("OpenAPI contracts help:", "Define and validate expected inputs in testing.", "Document auth schemes."),
    z("Canary deployments reduce:", "Blast radius of bad releases.", "Pair with monitoring and rollback."),
    z("Database encryption at rest protects:", "Stolen media scenarios; applications still need access control.", "Manage keys carefully."),
    z("Application-level encryption can protect:", "Sensitive fields even from DBAs depending on threat model.", "Key distribution is hard."),
    z("Secure deserialization guidelines:", "Use safe formats and avoid unsafe native pickling.", "Validate schemas."),
    z("API rate limits help:", "Reduce brute force and scraping abuse.", "Combine with auth and fraud signals."),
    z("Secure release signing:", "Verifies artifact integrity before deployment.", "Part of supply chain controls."),
    z("Environment variables for secrets:", "Are better than code but still extractable on hosts.", "Prefer secret managers."),
    z("Feature flags can expose:", "Incomplete features if misconfigured publicly.", "Gate and monitor."),
    z("A/B testing can leak:", "Sensitive experiment parameters if mishandled.", "Treat as data handling."),
    z("Fuzzing in CI can:", "Catch robustness issues early.", "Combine with sanitizers in dev builds."),
    z("Regression suites should include:", "Security tests for fixed vulnerabilities.", "Prevent comebacks."),
    z("Secure coding training reduces:", "Common vulnerability classes over time.", "Measure with metrics."),
    z("Security champions help scale:", "Reviews and awareness inside dev teams.", "Lightweight governance."),
    z("Threat intelligence in AppSec:", "Prioritizes fixes based on exploited vuln classes in your stack.", "Contextualize CVEs."),
    z("Vendor library SLAs affect:", "How quickly you can patch transitive dependencies.", "Contract for criticals."),
    z("Pen test findings remediation:", "Should be tracked like other defects with SLA owners.", "Don’t ignore “medium” forever."),
    z("SBOM consumption in operations:", "Accelerates vulnerability triage when a new CVE drops.", "Needs accurate component detection."),
    z("Developer laptops should:", "Be hardened and avoid storing production secrets.", "Use vaults and short-lived creds."),
]

# Lengths verified in build_extra_questions.py
